"""Phase 11 acceptance test: the creative auto-editing engine.

Three scenarios over three deliberately different libraries, each one driven end
to end through the running stack:

    upload 12 clips
        -> ingest        (the unchanged Phase 2 pipeline)
        -> analysis      (the unchanged CPU and GPU lanes)
        -> events        (Phase 11, derived from those analyses)
        -> story         (roles assigned from a genre policy)
        -> selection     (creative: quality, diversity, role, energy, style)
        -> pacing        (an energy curve, turned into per-shot lengths)
        -> decisions     (trims, speed, transitions, beat placement)
        -> EditPlan      (the unchanged Phase 4 document)
        -> validate      (the unchanged Phase 4 gate)
        -> render        (the unchanged Phase 9 pipeline)
        -> MP4           (ffprobe, and a full decode pass)

**The claim under test is not "it produces a video".** Phase 4 proved that. What
this proves is that the result is *not describable as "pick N clips and
concatenate them"*, and it does so with assertions that would fail if it were:

- shot lengths vary across the edit, and vary differently per genre;
- near-identical clips are rejected as repeats, not merely ranked lower;
- the strongest moment is given the peak role and emphasised;
- the order is the arc's, and where it departs from the shoot order it says so;
- football, nature and gaming produce materially different edits of comparable
  footage -- different counts, different lengths, different treatment;
- and the requested duration is still honoured.

Every clip is generated locally with FFmpeg. No network, no model weights, no
copyrighted bytes.

Run with infrastructure, the API, a cpu worker, a gpu worker and a render worker
up::

    python scripts/e2e_editorial.py                # all three scenarios
    python scripts/e2e_editorial.py football       # one at a time

**Run the scenarios one at a time on a memory-constrained machine.** Each builds
twelve clips, analyses them and renders an MP4; three at once is three FFmpeg
encodes and three analyzer passes competing for 7.4 GB.

Exits non-zero if any check fails.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

import httpx

API = os.environ.get("VF_API_URL", "http://127.0.0.1:8000")
CLIP_DIR = Path(os.environ.get("VF_E2E_CLIPS", Path(__file__).parent / ".e2e-clips"))
JOB_TIMEOUT_S = 1200

#: The duration every scenario asks for.
#:
#: Not 30 seconds, and the reason is worth stating because the number looks
#: arbitrary. These libraries are generated by FFmpeg, and CLIP -- which keys on
#: structure rather than on colour -- resolves everything ``lavfi`` can draw into
#: about four kinds of picture: test card, fractal, cellular and Sierpinski. A
#: synthetic library therefore yields four or five *editorially distinct* shots
#: however many files it contains. That is a property of the fixture, not of the
#: engine, and real footage is semantically far wider.
#:
#: What matters is where that lands relative to a policy's ceiling on shot
#: length. Football holds a shot for at most six seconds, so at a target of
#: exactly 24 or 30 seconds a four- or five-shot edit has to put *every* shot on
#: the ceiling -- and there a correct pacing model and a naive even split emit
#: identical output, so asserting that lengths vary tests nothing and fails
#: against a working engine. Twenty seconds is a multiple of none of the
#: ceilings in play (6000 football, 3500 gaming, 11000 nature), so every scenario
#: has room for the curve to shape, and the same assertions then tell the two
#: apart.
TARGET_MS = 20_000

PASS, FAIL, INFO = "PASS", "FAIL", " ..."
_failures: list[str] = []
_report: dict[str, object] = {}


def check(label: str, condition: bool, detail: str = "") -> None:
    print(f"  [{PASS if condition else FAIL}] {label}{(' - ' + detail) if detail else ''}")
    if not condition:
        _failures.append(label)


def note(label: str, detail: str = "") -> None:
    print(f"  [{INFO}] {label}{(' - ' + detail) if detail else ''}")


def step(title: str) -> None:
    print(f"\n{title}")


def ffmpeg() -> str:
    binary = shutil.which("ffmpeg")
    if binary is None:
        print("ffmpeg not on PATH")
        sys.exit(2)
    return binary


# ---------------------------------------------------------------------- inputs
@dataclass(frozen=True)
class ClipSpec:
    """One generated clip, and what it is supposed to be editorially.

    ``pattern`` is a distinct lavfi generator, and it carries two jobs. It has
    to be *textured*, because the Phase 3 quality gate measures focus as the
    variance of a Laplacian and a flat field of colour scores zero -- a library
    of solid colours is a library the planner never sees, having correctly
    thrown all of it away as blurred. And it has to be *unlike the others*,
    because the diversity term compares CLIP vectors, and a wall of navy and a
    wall of dark green are the same picture to CLIP however different their hues
    look to us.

    ``motion`` is a dial from 0 to 1 rather than a property of the generator.
    The frame is panned across a larger source at an amplitude and rate derived
    from it, so the dynamics analyzer *measures* movement that was put there on
    purpose and the ordering the scenario asserts -- the peak is the busiest
    shot in the edit -- is a fact about the footage rather than an accident of
    which generator happened to churn hardest.

    ``subject`` groups clips the semantic gate should treat as one shot: specs
    sharing a subject are built from the same generator, and differ only in how
    the frame moves over it, which is what two angles on one goal actually are.
    """

    name: str
    pattern: str
    duration_s: float
    subject: int
    motion: float
    rate: int = 25


def _source(pattern: str, rate: int) -> str:
    """One lavfi source description, generated larger than the output.

    The extra margin is what the pan crops out of. The length is *not* set here:
    several generators -- ``mandelbrot`` among them -- have no ``duration``
    option at all, so length is imposed with ``-t`` on the command line, which
    works for every source and produces exactly the same file.
    """
    separator = ":" if "=" in pattern else "="
    return f"{pattern}{separator}size=960x540:rate={rate}"


def _pan(motion: float, phase: float = 0.0) -> str:
    """A crop that moves, at a speed and distance set by ``motion``.

    Both amplitude and frequency rise with the dial, because a slow wide drift
    and a fast small jitter are both "some movement" to a frame-difference
    measure and neither on its own separates a held landscape from a goalmouth
    scramble. No commas anywhere in the expressions: a comma inside an unquoted
    filter argument ends the filter, and these are passed to FFmpeg as argv
    rather than through a shell that could quote them.
    """
    # Zero means *still*, not "barely moving": a fine texture saturates the
    # frame-difference measure at a six-pixel drift as readily as at a hundred,
    # so a floor under the amplitude would take the calm end of the dial away.
    amplitude = motion * 145.0
    speed = 0.30 + motion * 4.0
    x = f"(iw-ow)/2+{amplitude:.1f}*sin(t*{speed:.2f}+{phase:.2f})"
    y = f"(ih-oh)/2+{amplitude * 0.6:.1f}*cos(t*{speed * 0.7:.2f}+{phase:.2f})"
    return f"crop=640:360:x='{x}':y='{y}'"


#: Generators whose output is smooth -- ``gradients`` and ``colorspectrum``
#: among them -- are absent from every table below, and the absence is
#: deliberate. Phase 3 measures focus as the variance of a Laplacian, a smooth
#: wash of colour has almost no edges in it, and such a clip scores around 2
#: against the hundreds a textured frame scores. The planner never sees it: the
#: Phase 4 gate has already discarded it as out of focus, correctly. A fixture
#: built from them tests that gate and nothing after it.
#:
#: The opposite extreme matters just as much, and fixes the motion dial's
#: meaning. A very fine texture -- ``cellauto``, ``life``, a Sierpinski carpet --
#: changes every pixel when it moves even one, so frame difference saturates at
#: any pan speed at all and such a clip measures 1.0 whatever the dial says.
#: Every table below therefore follows one rule, so that "the busiest shot" is a
#: fact rather than a coincidence of which generator churns hardest: fine
#: textures are held perfectly still and form the calm end of every library, test
#: cards are panned in the middle of the range, and exactly one family per table
#: is panned hard enough to be the busiest thing in it, with nothing else near
#: it. Which family that is differs by scenario, because the busiest shot in a
#: football library is a repeated one and the busiest shot in a nature library
#: must not be.


def football_specs() -> list[ClipSpec]:
    """Context, a build of action, one strongest moment, a reaction, an ending.

    The peak trio is the library's one hard-panned fine texture, which is what
    makes the strongest moment strongest *by measurement*: it saturates the
    motion signal and nothing else comes close. It is also one generator at
    three framings and three lengths -- the "ten angles on one goal" case that a
    technical ranker cannot tell from ten different goals. Three distinct files,
    because ingest deduplicates on sha256 and byte-identical clips would never
    reach a selector at all; how far down the chain they are then caught is the
    system's business, and both the perceptual-hash gate and the editorial
    diversity term are legitimate places to catch them.
    """
    return [
        ClipSpec("fb_00_wide.mp4", "smptehdbars", 8, 0, motion=0.05),
        ClipSpec("fb_01_wide2.mp4", "cellauto=rule=110", 8, 1, motion=0.0),
        ClipSpec("fb_02_build.mp4", "testsrc", 7, 2, motion=0.40),
        ClipSpec("fb_03_build.mp4", "mandelbrot", 7, 3, motion=0.55),
        ClipSpec("fb_04_peak.mp4", "sierpinski=type=carpet", 6.0, 4, motion=1.0),
        ClipSpec("fb_05_peak_angle.mp4", "sierpinski=type=carpet", 6.4, 4, motion=0.97),
        ClipSpec("fb_06_peak_angle.mp4", "sierpinski=type=carpet", 6.8, 4, motion=0.95),
        ClipSpec("fb_07_action.mp4", "testsrc2", 6, 7, motion=0.50),
        ClipSpec("fb_08_action.mp4", "rgbtestsrc", 6, 8, motion=0.35),
        ClipSpec("fb_09_crowd.mp4", "life=mold=10:ratio=0.1", 7, 9, motion=0.0),
        ClipSpec("fb_10_calm.mp4", "pal75bars", 8, 10, motion=0.15),
        ClipSpec("fb_11_end.mp4", "cellauto=rule=30", 8, 11, motion=0.0),
    ]


def nature_specs() -> list[ClipSpec]:
    """Twelve long, calm, visually distinct holds. Nothing here is action.

    Distinct generators rather than distinct colours: CLIP keys on structure, so
    twelve washes of green and blue are one picture to it -- and no picture at
    all to a focus measure, which is what the first version of this fixture was.
    Every dial is low and the fine textures are held still, so there is no busy
    shot anywhere in the library for the policy to find.
    """
    sources = [
        ("smptebars", 0.05), ("testsrc", 0.10), ("mandelbrot", 0.20),
        ("sierpinski=type=carpet", 0.0), ("rgbtestsrc", 0.08), ("pal100bars", 0.06),
        ("life=mold=20:ratio=0.05", 0.0), ("testsrc2", 0.12),
        ("cellauto=rule=110", 0.0), ("pal75bars", 0.07),
        ("sierpinski=type=triangle", 0.0),
        ("smptehdbars", 0.09),
    ]
    return [
        ClipSpec(f"nt_{index:02d}.mp4", pattern, 10, index, motion=motion)
        for index, (pattern, motion) in enumerate(sources)
    ]


def gaming_specs() -> list[ClipSpec]:
    """Sixteen busy, saturated, high-frame-rate captures.

    Sixteen rather than twelve, because this is the scenario that asserts the
    edit *cuts often*, and a policy that wants a shot every 1.4 seconds needs
    candidates to spend. Gaming's policy also tolerates repetition -- one arena
    looks like the same arena all match -- so this is deliberately the library
    where the diversity floor does least and the shot count is set by the pacing.

    The colour bars are panned barely at all, and that is a focus constraint
    rather than an editorial one. A bar pattern is a few large flat blocks, so a
    crop that wanders far enough into one sees no edges, scores near zero on a
    Laplacian and is discarded as out of focus before the planner ever sees it.
    Detail-rich sources -- ``testsrc``, ``mandelbrot`` -- carry texture
    everywhere and can be thrown around freely.
    """
    sources = [
        # Detail everywhere: safe to pan hard. ``testsrc`` at full dial is the
        # busiest thing here and the only clip near that end, so the peak is the
        # peak by measurement.
        ("testsrc", 1.0), ("testsrc2", 0.55), ("testsrc", 0.50), ("testsrc2", 0.45),
        ("mandelbrot", 0.50), ("mandelbrot", 0.40),
        # Fine textures: held still, because panning one saturates the motion
        # measure at any speed and would leave the edit with several equally
        # "busiest" shots and no way to tell which is the peak.
        ("life=mold=10", 0.0), ("life=mold=20:ratio=0.2", 0.0),
        ("cellauto=rule=90", 0.0), ("cellauto=rule=30", 0.0),
        ("cellauto=rule=110", 0.0), ("cellauto=rule=150", 0.0),
        ("sierpinski=type=carpet", 0.0), ("sierpinski=type=triangle", 0.0),
        # Flat blocks: barely panned, for the reason in the docstring.
        ("smptebars", 0.10), ("smptehdbars", 0.08),
    ]
    return [
        ClipSpec(f"gm_{index:02d}.mp4", pattern, 6, index, motion=motion, rate=50)
        for index, (pattern, motion) in enumerate(sources)
    ]


def build_clips(specs: list[ClipSpec]) -> list[Path]:
    """Generate every clip once and cache it on disk.

    Two steps, and the first one is the point. A single frame of the generator
    is frozen to a PNG, and the clip is that still panned by :func:`_pan`. Built
    straight from the moving generator instead, the *generator's* churn is what
    the dynamics analyzer measures -- ``life`` repaints every cell each step and
    ``mandelbrot`` zooms continuously, so a clip nominally dialled to 0.6 moves
    more than one dialled to 1.0, and an assertion that the peak is the busiest
    shot in the edit then depends on which generator happens to churn hardest
    rather than on anything editorial. Freezing the frame first makes the dial
    the only source of movement, which is what it was supposed to be.

    ``-preset ultrafast`` and 640x360 deliberately: these are inputs to an
    editorial decision, not output quality, and a scenario that takes six
    minutes to *generate* is one nobody runs.

    The recipe is cached beside the clip, and a clip whose recipe has changed is
    rebuilt. Caching on filename alone means editing this file silently keeps
    the previous library, and a fixture that does not match its own source is
    the worst kind of green.
    """
    CLIP_DIR.mkdir(parents=True, exist_ok=True)
    binary = ffmpeg()
    built: list[Path] = []
    for index, spec in enumerate(specs):
        destination = CLIP_DIR / spec.name
        recipe_path = destination.with_suffix(".recipe")
        still = destination.with_suffix(".png")
        freeze = [
            binary, "-y", "-loglevel", "error",
            "-f", "lavfi", "-i", _source(spec.pattern, spec.rate),
            "-frames:v", "1", str(still),
        ]
        encode = [
            binary, "-y", "-loglevel", "error",
            "-loop", "1", "-i", str(still),
            "-t", str(spec.duration_s), "-r", str(spec.rate),
            "-vf", _pan(spec.motion, phase=index * 1.7),
            "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p", "-an",
            str(destination),
        ]
        recipe = " ".join(freeze[1:-1] + encode[1:-1])
        stale = (
            not destination.exists()
            or not recipe_path.exists()
            or recipe_path.read_text(encoding="utf-8") != recipe
        )
        if stale:
            subprocess.run(freeze, check=True, capture_output=True, timeout=300)
            subprocess.run(encode, check=True, capture_output=True, timeout=300)
            recipe_path.write_text(recipe, encoding="utf-8")
        built.append(destination)
    return built


# --------------------------------------------------------------------- helpers
def create_project(title: str) -> str:
    response = httpx.post(f"{API}/api/projects", json={"title": title}, timeout=30)
    response.raise_for_status()
    return str(response.json()["id"])


def upload(project_id: str, path: Path) -> tuple[str, str | None]:
    ticket = httpx.post(
        f"{API}/api/projects/{project_id}/media/upload-url",
        json={"filename": path.name, "size_bytes": path.stat().st_size},
        timeout=30,
    )
    ticket.raise_for_status()
    body = ticket.json()

    httpx.put(body["upload_url"], content=path.read_bytes(), timeout=300).raise_for_status()
    completed = httpx.post(
        f"{API}/api/projects/{project_id}/media/{body['media_id']}/complete", timeout=60
    )
    completed.raise_for_status()
    return body["media_id"], completed.json().get("job_id")


def wait_for_job(job_id: str, timeout_s: int = JOB_TIMEOUT_S) -> dict:
    deadline = time.monotonic() + timeout_s
    last: dict = {}
    while time.monotonic() < deadline:
        last = httpx.get(f"{API}/api/jobs/{job_id}", timeout=30).json()
        if last["status"] in {"succeeded", "failed", "cancelled"}:
            return last
        time.sleep(0.5)
    raise TimeoutError(f"job {job_id} stuck in {last.get('status')} after {timeout_s}s")


def wait_for_render(project_id: str, render_id: str, timeout_s: int = JOB_TIMEOUT_S) -> dict:
    deadline = time.monotonic() + timeout_s
    last: dict = {}
    while time.monotonic() < deadline:
        last = httpx.get(f"{API}/api/projects/{project_id}/renders/{render_id}", timeout=30).json()
        if last["status"] in {"ready", "failed", "cancelled"}:
            return last
        time.sleep(1.0)
    raise TimeoutError(f"render {render_id} stuck in {last.get('status')}")


def ffprobe(path: Path) -> dict:
    binary = shutil.which("ffprobe")
    if binary is None:
        print("ffprobe not on PATH")
        sys.exit(2)
    result = subprocess.run(
        [binary, "-v", "error", "-print_format", "json", "-show_format", "-show_streams",
         str(path)],
        check=True, capture_output=True, timeout=120,
    )
    return json.loads(result.stdout)


def make_plan(project_id: str, **overrides: object) -> dict:
    """One plan, with everything but the overrides held constant."""
    body: dict[str, object] = {
        "mode": "rules",
        "target_duration_ms": TARGET_MS,
        "max_clips": 12,
        "min_clips": 3,
        "aspect_ratio": "16:9",
        "fps": 30,
        "quality": "draft",
    }
    body.update(overrides)
    response = httpx.post(
        f"{API}/api/projects/{project_id}/edit-plan", json=body, timeout=300
    )
    response.raise_for_status()
    return response.json()


# ------------------------------------------------------------------- scenarios
def scenario_media(title: str, specs: list[ClipSpec]) -> tuple[str, list[str]]:
    step(f"1. MEDIA - import {len(specs)} clips for the {title} scenario")

    clips = build_clips(specs)
    project_id = create_project(f"Phase 11 {title}")
    note("project", project_id)

    media_ids: list[str] = []
    for path in clips:
        media_id, job_id = upload(project_id, path)
        media_ids.append(media_id)
        if job_id:
            outcome = wait_for_job(job_id)
            if outcome["status"] != "succeeded":
                check(f"ingest {path.name}", False, str(outcome.get("error")))

    ready = httpx.get(f"{API}/api/projects/{project_id}/media", timeout=60).json()
    landed = {item["id"] for item in ready["items"] if item["status"] == "ready"}
    check("every clip ingested", len(landed) == len(specs), f"{len(landed)}/{len(specs)} ready")
    # Whatever actually landed is what the rest of the scenario talks about: an
    # upload that was rejected is not a clip the planner can be asked about.
    return project_id, [media_id for media_id in media_ids if media_id in landed]


def scenario_analysis(project_id: str, media_ids: list[str]) -> None:
    step("2. ANALYSIS - the unchanged CPU and GPU lanes")

    queued = httpx.post(f"{API}/api/projects/{project_id}/analysis", json={}, timeout=120)
    check("analysis accepted", queued.status_code == 202, str(queued.status_code))
    if queued.status_code != 202:
        return

    jobs = [job["id"] for job in queued.json().get("jobs", [])]
    failed = 0
    for job_id in jobs:
        outcome = wait_for_job(job_id)
        if outcome["status"] != "succeeded":
            failed += 1
    check("every analysis job succeeded", failed == 0, f"{failed} failed of {len(jobs)}")

    # What the editorial layer actually needs on disk. Motion and colour come
    # from the Phase 8 dynamics analyzer and the vector from the GPU lane; an
    # edit planned without either still works, and is a weaker edit, so the
    # scenario reports the coverage rather than assuming it.
    present = {"dynamics": 0, "clip": 0, "quality": 0, "scenes": 0}
    for media_id in media_ids:
        rows = httpx.get(
            f"{API}/api/projects/{project_id}/media/{media_id}/analysis", timeout=30
        ).json()
        for row in rows["items"]:
            if row["status"] == "ok" and row["analyzer"] in present:
                present[row["analyzer"]] += 1
    for analyzer, seen in present.items():
        check(f"{analyzer} analysed every clip", seen == len(media_ids),
              f"{seen}/{len(media_ids)}")


def describe(plan: dict) -> None:
    """Print the editorial plan the way the editor draws it."""
    editorial = plan.get("editorial")
    if not editorial:
        return
    note("policy", f"{editorial['policy']} / arc {editorial['arc']} / "
                   f"pacing {editorial['pacing']['curve']['shape']}")
    for segment in editorial["segments"]:
        reasons = ", ".join(segment["reasons"][:3])
        effects = ",".join(effect["kind"] for effect in segment["effects"]) or "-"
        print(
            f"        {segment['slot']:>2} {segment['role']:<9}"
            f" src#{segment['sequence']:<3}"
            f" {segment['output_ms']:>6} ms"
            f" E={segment['energy']:.2f}/{segment['target_energy']:.2f}"
            f" {segment['transition']:<14} fx={effects:<12} {reasons}"
        )
    measured = {
        name: metric["value"]
        for name, metric in editorial["metrics"].items()
        if metric["value"] is not None
    }
    note("metrics", json.dumps(measured))


def scenario_editorial(project_id: str, policy: str, media_ids: list[str]) -> dict:
    step(f"3. EDITORIAL - plan under the {policy} policy")

    plan = make_plan(project_id, editorial_policy=policy)
    describe(plan)

    editorial = plan.get("editorial")
    check("the plan carries an editorial account", editorial is not None)
    if editorial is None:
        return plan

    segments = editorial["segments"]
    check("the edit has several shots", len(segments) >= 3, str(len(segments)))

    # --- not a concatenation: the lengths differ ---
    lengths = [segment["output_ms"] for segment in segments]
    check("shot lengths vary", len(set(lengths)) > 1,
          f"{min(lengths)}-{max(lengths)} ms")
    check(
        "the longest shot is meaningfully longer than the shortest",
        max(lengths) >= min(lengths) * 1.25,
        f"{max(lengths) / max(min(lengths), 1):.2f}x",
    )

    # --- not a concatenation: clips were declined on editorial grounds ---
    rejected = editorial["rejected"]
    check("some clips were not used", len(rejected) > 0, f"{len(rejected)} declined")
    reasons = {reason for item in rejected for reason in item["reasons"]}
    note("reasons for declining", ", ".join(sorted(reasons)) or "none")

    # --- roles ---
    roles = [segment["role"] for segment in segments]
    check("every shot has a narrative role", all(roles), ", ".join(roles))
    check("the edit has a peak", "peak" in roles)
    order = ["hook", "setup", "build", "peak", "reaction", "ending"]
    positions = [order.index(role) for role in roles]
    check("the roles run in narrative order", positions == sorted(positions))

    # --- the peak is the busiest thing in it ---
    busiest = max(segments, key=lambda segment: segment["energy"])
    check("the busiest shot is the peak", busiest["role"] == "peak",
          f"busiest is {busiest['role']}")

    # --- explainability ---
    check("every shot says why it was chosen",
          all(segment["reasons"] for segment in segments))

    # --- the duration the caller asked for ---
    total = plan["total_duration_ms"]
    check(
        "the requested duration is respected",
        abs(total - TARGET_MS) <= TARGET_MS * 0.2,
        f"{total} ms of {TARGET_MS}",
    )

    _report[f"{policy}_segments"] = len(segments)
    _report[f"{policy}_duration_ms"] = total
    _report[f"{policy}_lengths"] = lengths
    _report[f"{policy}_roles"] = roles
    return plan


def scenario_duplicates(plan: dict, repeated: list[str]) -> None:
    """The "ten angles on one goal" case, over real analysed footage."""
    step("4. DIVERSITY - near-identical clips are declined as repeats")

    editorial = plan.get("editorial")
    if editorial is None:
        check("an editorial plan exists", False)
        return

    used = [s for s in editorial["segments"] if s["media_id"] in repeated]
    check(
        "the repeated moment contributes at most two shots",
        len(used) <= 2,
        f"{len(used)} of {len(repeated)} angles used",
    )
    named = [item for item in editorial["rejected"] if item.get("similar_to")]
    check("a declined clip names what it repeats", len(named) > 0,
          f"{len(named)} named")


def scenario_variants(project_id: str, policy: str) -> None:
    step("5. VARIANTS - three alternatives, previewed and not stored")

    before = httpx.get(f"{API}/api/projects/{project_id}/edit-plan", timeout=30).json()["total"]
    response = httpx.post(
        f"{API}/api/projects/{project_id}/edit-plan/variants",
        json={
            "mode": "rules",
            "target_duration_ms": TARGET_MS,
            "max_clips": 12,
            "min_clips": 3,
            "editorial_policy": policy,
        },
        timeout=300,
    )
    check("the variants route answered", response.status_code == 200, str(response.status_code))
    if response.status_code != 200:
        return

    items = response.json()["items"]
    check("four alternatives came back", len(items) == 4, str(len(items)))

    signatures = {
        tuple((s["media_id"], s["output_ms"]) for s in item["editorial"]["segments"])
        for item in items
    }
    check("every alternative is a different decision set", len(signatures) == len(items),
          f"{len(signatures)} distinct of {len(items)}")

    for item in items:
        note(
            item["label"],
            f"{item['clip_count']} shots, {item['total_duration_ms']} ms, "
            f"pacing {item['editorial']['pacing']['curve']['shape']}",
        )

    after = httpx.get(f"{API}/api/projects/{project_id}/edit-plan", timeout=30).json()["total"]
    check("nothing was stored", after == before, f"{before} -> {after} plans")


def scenario_render(project_id: str, plan: dict, name: str) -> Path | None:
    step("6. RENDER - the editorial plan, through the unchanged pipeline")

    queued = httpx.post(
        f"{API}/api/projects/{project_id}/render",
        json={"edit_plan_id": plan["id"]},
        timeout=60,
    )
    check("render queued", queued.status_code == 202, str(queued.status_code))
    if queued.status_code != 202:
        return None

    render_id = queued.json()["id"]
    started = time.monotonic()
    render = wait_for_render(project_id, render_id)
    elapsed_ms = int((time.monotonic() - started) * 1000)
    check("render succeeded", render["status"] == "ready", str(render.get("error")))
    if render["status"] != "ready":
        return None

    detail = httpx.get(f"{API}/api/projects/{project_id}/renders/{render_id}", timeout=30).json()
    url = detail.get("playback_url")
    check("a presigned playback URL is issued", bool(url))
    if not url:
        return None

    output = CLIP_DIR / f"phase11_{name}.mp4"
    output.write_bytes(httpx.get(url, timeout=600).content)
    check("the file downloaded", output.stat().st_size > 0, f"{output.stat().st_size} bytes")

    _report[f"{name}_render_ms"] = elapsed_ms
    _report[f"{name}_output"] = str(output)
    return output


def scenario_verify(output: Path, plan: dict) -> None:
    step("7. MP4 - verified independently with ffprobe")

    probe = ffprobe(output)
    video = next((s for s in probe["streams"] if s["codec_type"] == "video"), None)
    check("a video stream exists", video is not None)
    if video is None:
        return

    check("container is mp4", "mp4" in probe["format"]["format_name"],
          probe["format"]["format_name"])
    check("video codec is h264", video["codec_name"] == "h264", video["codec_name"])
    check("resolution is 1280x720", (video["width"], video["height"]) == (1280, 720),
          f"{video['width']}x{video['height']}")

    duration_ms = int(float(probe["format"]["duration"]) * 1000)
    planned = plan["total_duration_ms"]
    check(
        "the file is as long as the plan said",
        abs(duration_ms - planned) <= max(600, planned * 0.06),
        f"{duration_ms} ms vs planned {planned} ms",
    )

    binary = shutil.which("ffmpeg")
    assert binary is not None
    decode = subprocess.run(
        [binary, "-v", "error", "-xerror", "-i", str(output), "-f", "null", "-"],
        capture_output=True, timeout=900,
    )
    check("the file decodes completely", decode.returncode == 0)


# -------------------------------------------------------------- the scenarios
def run_football() -> dict:
    print("\n" + "=" * 68)
    print("SCENARIO A - Football")
    print("=" * 68)

    specs = football_specs()
    project_id, media_ids = scenario_media("football", specs)
    scenario_analysis(project_id, media_ids)

    plan = scenario_editorial(project_id, "football", media_ids)
    repeated = [media_ids[index] for index, spec in enumerate(specs) if spec.subject == 4]
    scenario_duplicates(plan, repeated)

    editorial = plan.get("editorial") or {}
    segments = editorial.get("segments", [])
    peaks = [segment for segment in segments if segment["role"] == "peak"]
    check("the peak is emphasised or slowed", any(
        segment["effects"] or segment["output_ms"] > segment["duration_ms"]
        for segment in peaks
    ), f"{len(peaks)} peak shot(s)")

    scenario_variants(project_id, "football")
    output = scenario_render(project_id, plan, "football")
    if output is not None:
        scenario_verify(output, plan)
    return plan


def run_nature() -> dict:
    print("\n" + "=" * 68)
    print("SCENARIO B - Nature")
    print("=" * 68)

    specs = nature_specs()
    project_id, media_ids = scenario_media("nature", specs)
    scenario_analysis(project_id, media_ids)

    plan = scenario_editorial(project_id, "nature", media_ids)
    editorial = plan.get("editorial") or {}
    segments = editorial.get("segments", [])

    if segments:
        mean = sum(segment["output_ms"] for segment in segments) / len(segments)
        check("shots are held for several seconds", mean >= 2_500, f"mean {mean:.0f} ms")
        check(
            "the opening is one of the longer shots",
            segments[0]["output_ms"] >= mean * 0.9,
            f"{segments[0]['output_ms']} ms vs mean {mean:.0f} ms",
        )
        check(
            "dissolves are used where the edit settles",
            any(segment["transition"] != "cut" for segment in segments),
        )
        check(
            "no shot is sped up or slowed",
            not any(
                effect["kind"] in {"slow_motion", "speed_up"}
                for segment in segments
                for effect in segment["effects"]
            ),
        )

    output = scenario_render(project_id, plan, "nature")
    if output is not None:
        scenario_verify(output, plan)
    return plan


def run_gaming() -> dict:
    print("\n" + "=" * 68)
    print("SCENARIO C - Gaming")
    print("=" * 68)

    specs = gaming_specs()
    project_id, media_ids = scenario_media("gaming", specs)
    scenario_analysis(project_id, media_ids)

    plan = scenario_editorial(project_id, "gaming", media_ids)
    editorial = plan.get("editorial") or {}
    segments = editorial.get("segments", [])

    if segments:
        mean = sum(segment["output_ms"] for segment in segments) / len(segments)
        check("shots are short", mean <= 5_000, f"mean {mean:.0f} ms")
        check("the edit cuts often", len(segments) >= 6, f"{len(segments)} shots")
        check(
            "energy rises into the peak",
            editorial["pacing"]["curve"]["shape"] in {"build", "ramp"},
            editorial["pacing"]["curve"]["shape"],
        )

    output = scenario_render(project_id, plan, "gaming")
    if output is not None:
        scenario_verify(output, plan)
    return plan


def compare(plans: dict[str, dict]) -> None:
    """The acceptance criterion the whole phase turns on.

    Three genres, three comparable libraries, three materially different edits.
    If this passes while the individual scenarios pass, the system cannot be
    described as "select clips and concatenate them" -- because the same
    pipeline, given the same kind of footage, produced three different cuts of
    it and the only thing that changed was a table of numbers.
    """
    step("8. COMPARISON - the genres produce materially different edits")

    shapes: dict[str, tuple[int, float, str]] = {}
    for name, plan in plans.items():
        editorial = plan.get("editorial")
        if not editorial or not editorial["segments"]:
            continue
        segments = editorial["segments"]
        mean = sum(segment["output_ms"] for segment in segments) / len(segments)
        shapes[name] = (len(segments), mean, editorial["pacing"]["curve"]["shape"])
        note(name, f"{len(segments)} shots, mean {mean:.0f} ms, "
                   f"pacing {editorial['pacing']['curve']['shape']}")

    if "nature" in shapes and "gaming" in shapes:
        check(
            "nature holds its shots longer than gaming",
            shapes["nature"][1] > shapes["gaming"][1] * 1.3,
            f"{shapes['nature'][1]:.0f} ms vs {shapes['gaming'][1]:.0f} ms",
        )
        check(
            "gaming cuts more often than nature",
            shapes["gaming"][0] > shapes["nature"][0],
            f"{shapes['gaming'][0]} vs {shapes['nature'][0]} shots",
        )
    if len(shapes) >= 2:
        check(
            "no two genres produced the same shape",
            len({(count, round(mean / 250)) for count, mean, _ in shapes.values()})
            == len(shapes),
            json.dumps({k: [v[0], round(v[1])] for k, v in shapes.items()}),
        )

    _report["comparison"] = {k: [v[0], round(v[1]), v[2]] for k, v in shapes.items()}


SCENARIOS = {"football": run_football, "nature": run_nature, "gaming": run_gaming}


def main() -> int:
    print("VisionForge - Phase 11 acceptance (creative auto-editing engine)")
    print("=" * 68)

    wanted = [name for name in sys.argv[1:] if name in SCENARIOS] or list(SCENARIOS)
    if len(wanted) > 1:
        print(
            "Running all three scenarios. On a memory-constrained machine, run "
            "them one at a time:\n"
            "    python scripts/e2e_editorial.py football\n"
        )

    try:
        httpx.get(f"{API}/health", timeout=10).raise_for_status()
    except Exception as exc:  # noqa: BLE001 - the script reports and exits
        print(f"API not reachable at {API}: {exc}")
        return 2

    plans: dict[str, dict] = {}
    for name in wanted:
        # One scenario at a time, deliberately. Each analyses twelve clips and
        # renders an MP4; running them concurrently would put three FFmpeg
        # encodes and three analyzer passes against 7.4 GB of RAM.
        plans[name] = SCENARIOS[name]()

    if len(plans) > 1:
        compare(plans)

    print("\n" + "=" * 68)
    print(json.dumps(_report, indent=2, default=str))
    if _failures:
        print(f"\n{len(_failures)} check(s) failed:")
        for failure in _failures:
            print(f"  - {failure}")
        return 1
    print("\nAll checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
