"""media_analysis with pgvector embedding

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-12 12:44:32.247541
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_analysis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("media_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "analyzer",
            sa.Enum(
                "quality",
                "scenes",
                "phash",
                "clip",
                "faces",
                name="analyzername",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("analyzer_version", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ok", "unsupported", "failed", name="analysisstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["media_id"], ["media_assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "media_id", "analyzer", "analyzer_version", name="uq_analysis_media_analyzer_version"
        ),
    )
    op.create_index(
        "ix_analysis_media_analyzer", "media_analysis", ["media_id", "analyzer"], unique=False
    )
    op.create_index(
        "ix_analysis_project_analyzer", "media_analysis", ["project_id", "analyzer"], unique=False
    )
    op.create_index(
        op.f("ix_media_analysis_media_id"), "media_analysis", ["media_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_analysis_project_id"), "media_analysis", ["project_id"], unique=False
    )
    # ### end Alembic commands ###

    # HNSW approximate-nearest-neighbour index over the CLIP embeddings.
    # Autogenerate cannot emit this: it has no notion of vector opclasses.
    #
    # HNSW rather than IVFFlat because IVFFlat needs representative data present
    # before it can build meaningful lists, and this table starts empty. HNSW
    # builds incrementally and stays correct from the first row.
    #
    # vector_cosine_ops because CLIP embeddings are compared by cosine
    # similarity; the analyzer L2-normalises before storing, so cosine and inner
    # product agree.
    #
    # m=16 / ef_construction=64 are pgvector's defaults, kept deliberately: this
    # machine has 7.4 GB of RAM and a larger graph costs build memory for
    # accuracy no one has yet measured a need for.
    op.execute(
        "CREATE INDEX ix_analysis_embedding_hnsw ON media_analysis "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_analysis_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_analysis_project_id"), table_name="media_analysis")
    op.drop_index(op.f("ix_media_analysis_media_id"), table_name="media_analysis")
    op.drop_index("ix_analysis_project_analyzer", table_name="media_analysis")
    op.drop_index("ix_analysis_media_analyzer", table_name="media_analysis")
    op.drop_table("media_analysis")
    # ### end Alembic commands ###
