"""edit_plans and renders

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-12 14:32:02.698941
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edit_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("planner", sa.String(length=48), nullable=False),
        sa.Column("planner_version", sa.String(length=16), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selection", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_duration_ms", sa.Integer(), nullable=False),
        sa.Column("segment_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_edit_plans_project_created", "edit_plans", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_edit_plans_project_id"), "edit_plans", ["project_id"], unique=False)
    op.create_table(
        "renders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("edit_plan_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "rendering",
                "ready",
                "failed",
                "cancelled",
                name="renderstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column("bytes_size", sa.BigInteger(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("timeline", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["edit_plan_id"], ["edit_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_renders_edit_plan_id"), "renders", ["edit_plan_id"], unique=False)
    op.create_index(
        "ix_renders_project_created", "renders", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_renders_project_id"), "renders", ["project_id"], unique=False)
    op.create_index(op.f("ix_renders_status"), "renders", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_renders_status"), table_name="renders")
    op.drop_index(op.f("ix_renders_project_id"), table_name="renders")
    op.drop_index("ix_renders_project_created", table_name="renders")
    op.drop_index(op.f("ix_renders_edit_plan_id"), table_name="renders")
    op.drop_table("renders")
    op.drop_index(op.f("ix_edit_plans_project_id"), table_name="edit_plans")
    op.drop_index("ix_edit_plans_project_created", table_name="edit_plans")
    op.drop_table("edit_plans")
    # ### end Alembic commands ###
